apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ouv3hm2bx-nodejs 
  janus-idp.io/tekton: ouv3hm2bx-nodejs
  backstage.io/kubernetes-id: ouv3hm2bx-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ouv3hm2bx-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml