apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ouv3hm2bx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ouv3hm2bx-nodejs 
  name: ouv3hm2bx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ouv3hm2bx-nodejs 
